// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjpsmwtguucyrbbltryh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqcHNtd3RndXVjeXJiYmx0cnloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDgyMDEsImV4cCI6MjA1OTc4NDIwMX0.Y1HcZYJPk1iaHL8GjNpeFIMzO5ztYa1qu-TdtHK_hPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);